Repository optimizely/javascript-sdk, pull requests merged in 2019-11, with the labels that each got.

#366 fix: log error message when user allocated to vacated space in group or experiment
  packages/optimizely-sdk/lib/core/bucketer/index.js
  packages/optimizely-sdk/lib/core/bucketer/index.tests.js
  packages/optimizely-sdk/lib/core/decision_service/index.js
Labels: :robot: 24 hrs

#371 chore: Standardize subpackages on npm instead of yarn
  packages/datafile-manager/package-lock.json
  packages/datafile-manager/package.json
  packages/datafile-manager/yarn.lock
  packages/logging/yarn.lock
  packages/utils/yarn.lock
Labels: :robot: 4 hrs

#370 feat: Multi-client builds support
  .travis.yml
Labels: :robot: 20 hrs
