Repository optimizely/javascript-sdk, pull requests merged in 2020-07, with the labels that each got.

#521 Removes spell check of md files stage from travis.yml
  .travis.yml
Labels: :robot: 16 hrs

#522 ci: add source clear as a separate stage;
  .travis.yml
Labels: :robot: 8 hrs

#526 feat: Convert user_profile_service_validator module to TS
  packages/optimizely-sdk/lib/optimizely/index.js
  packages/optimizely-sdk/lib/utils/user_profile_service_validator/index.ts
Labels: :robot: 4 hrs

#532 feat: Integrate react native event processor with optimizely SDK
  packages/optimizely-sdk/lib/index.browser.tests.js
  packages/optimizely-sdk/lib/index.node.tests.js
  packages/optimizely-sdk/lib/index.react_native.js
  packages/optimizely-sdk/lib/index.react_native.tests.js
  packages/optimizely-sdk/lib/optimizely/index.js
  packages/optimizely-sdk/lib/optimizely/index.tests.js
  packages/optimizely-sdk/lib/plugins/event_dispatcher/index.browser.js
  packages/optimizely-sdk/package-lock.json
  packages/optimizely-sdk/package.json
Labels: :robot: 4 hrs

#528 feat: Convert event_tags_validator module to TS
  packages/optimizely-sdk/lib/optimizely/index.js
  packages/optimizely-sdk/lib/utils/event_tags_validator/index.ts
  packages/optimizely-sdk/lib/utils/user_profile_service_validator/index.ts
Labels: :robot: 4 hrs

#524 feat: Convert project_config_schema and json_schema_validator modules to TS
  packages/optimizely-sdk/lib/core/decision_service/index.tests.js
  packages/optimizely-sdk/lib/core/project_config/project_config_manager.tests.js
  packages/optimizely-sdk/lib/core/project_config/project_config_schema.ts
  packages/optimizely-sdk/lib/optimizely/index.tests.js
  packages/optimizely-sdk/lib/utils/json_schema_validator/index.ts
Labels: :robot: 4 hrs

#530 feat: Convert attributes_validator to TS
  packages/optimizely-sdk/lib/core/event_builder/event_helpers.js
  packages/optimizely-sdk/lib/core/event_builder/index.js
  packages/optimizely-sdk/lib/utils/attributes_validator/index.tests.js
  packages/optimizely-sdk/lib/utils/attributes_validator/index.ts
Labels: :robot: 24 hrs
