Repository optimizely/javascript-sdk, pull requests merged in 2020-02, with the labels that each got.

#401 chore: Prepare for event processor 0.4.0 release
  packages/event-processor/CHANGELOG.MD
  packages/event-processor/package-lock.json
  packages/event-processor/package.json
Labels: :robot: 4 hrs

#395 Removed dependency on lodash.assign
  packages/optimizely-sdk/lib/core/audience_evaluator/index.js
  packages/optimizely-sdk/lib/core/decision_service/index.js
  packages/optimizely-sdk/lib/core/project_config/index.js
  packages/optimizely-sdk/lib/index.browser.js
  packages/optimizely-sdk/lib/index.react_native.js
  packages/optimizely-sdk/lib/utils/fns/index.js
Labels: :robot: 8 hrs

#399 refactor: Removed dependency on lodash.forOwn
  packages/optimizely-sdk/lib/core/event_builder/event_helpers.js
  packages/optimizely-sdk/lib/core/event_builder/index.js
  packages/optimizely-sdk/lib/core/notification_center/index.js
  packages/optimizely-sdk/lib/core/project_config/index.js
  packages/optimizely-sdk/lib/optimizely/index.js
  packages/optimizely-sdk/lib/utils/attributes_validator/index.tests.js
  packages/optimizely-sdk/lib/utils/fns/index.js
Labels: :robot: 12 hrs
