Repository optimizely/javascript-sdk, pull requests merged in 2020-09, with the labels that each got.

#535 feat: datafile accessor
  packages/optimizely-sdk/.eslintrc.js
  packages/optimizely-sdk/lib/core/optimizely_config/index.js
  packages/optimizely-sdk/lib/core/optimizely_config/index.tests.js
  packages/optimizely-sdk/lib/core/project_config/index.js
  packages/optimizely-sdk/lib/core/project_config/index.tests.js
  packages/optimizely-sdk/lib/core/project_config/project_config_manager.js
  packages/optimizely-sdk/lib/core/project_config/project_config_manager.tests.js
  packages/optimizely-sdk/lib/index.browser.js
  packages/optimizely-sdk/lib/index.node.js
  packages/optimizely-sdk/lib/index.react_native.js
  packages/optimizely-sdk/lib/optimizely/index.js
  packages/optimizely-sdk/lib/utils/config_validator/index.ts
  packages/optimizely-sdk/package-lock.json
  packages/optimizely-sdk/package.json
Labels: :robot: 16 hrs

#564 fix(datafile accessor): Add datafile accessor method to TS definitions
  packages/optimizely-sdk/lib/index.d.ts
Labels: :robot: 4 hrs

#565 feat: Convert event_processor_config_validator to TS
  packages/optimizely-sdk/lib/utils/event_processor_config_validator/index.ts
Labels: :robot: 12 hrs

#567 feat: Created declaration file for project config index.d.ts module
  packages/optimizely-sdk/lib/core/condition_tree_evaluator/index.ts
  packages/optimizely-sdk/lib/core/project_config/entities.ts
  packages/optimizely-sdk/lib/core/project_config/index.d.ts
Labels: :robot: 8 hrs
