Repository optimizely/javascript-sdk, pull requests merged in 2021-05, with the labels that each got.

#659 feat: Convert decision service to TS
  packages/optimizely-sdk/lib/core/audience_evaluator/index.d.ts
  packages/optimizely-sdk/lib/core/audience_evaluator/index.js
  packages/optimizely-sdk/lib/core/audience_evaluator/index.tests.js
  packages/optimizely-sdk/lib/core/bucketer/index.ts
  packages/optimizely-sdk/lib/core/decision_service/index.d.ts
  packages/optimizely-sdk/lib/core/decision_service/index.js
  packages/optimizely-sdk/lib/core/decision_service/index.tests.js
  packages/optimizely-sdk/lib/core/decision_service/index.ts
  packages/optimizely-sdk/lib/core/project_config/index.ts
  packages/optimizely-sdk/lib/shared_types.ts
Labels: :robot: 24 hrs

#668 feat: Upgrade TypeScript to v4.0.3 in logging package
  .travis.yml
  packages/logging/package-lock.json
  packages/logging/package.json
Labels: :robot: 12 hrs

#666 update: Updated deprecated dependency for React Native
  .travis.yml
  packages/datafile-manager/CHANGELOG.md
  packages/datafile-manager/README.md
  packages/datafile-manager/__mocks__/@react-native-async-storage/async-storage.ts
  packages/datafile-manager/package-lock.json
  packages/datafile-manager/package.json
  packages/datafile-manager/src/reactNativeAsyncStorageCache.ts
  packages/event-processor/CHANGELOG.MD
  packages/event-processor/__mocks__/@react-native-async-storage/async-storage.ts
  packages/event-processor/__tests__/reactNativeEventsStore.spec.ts
  packages/event-processor/__tests__/v1EventProcessor.react_native.spec.ts
  packages/event-processor/package-lock.json
  packages/event-processor/package.json
  packages/event-processor/src/reactNativeAsyncStorageCache.ts
Labels: :robot: 24 hrs

#670 chore(datafile manager): Prepare for 0.8.1 release
  packages/datafile-manager/CHANGELOG.md
  packages/datafile-manager/package-lock.json
  packages/datafile-manager/package.json
Labels: :robot: 4 hrs

#671 chore(event processor): Prepare for 0.8.1 release
  packages/event-processor/CHANGELOG.MD
  packages/event-processor/package-lock.json
  packages/event-processor/package.json
Labels: :robot: 4 hrs
