Repository optimizely/javascript-sdk, pull requests merged in 2022-09, with the labels that each got.

#787 bug: Remove execution context determination
  packages/optimizely-sdk/lib/index.browser.ts
  packages/optimizely-sdk/lib/index.node.ts
  packages/optimizely-sdk/lib/index.react_native.ts
  packages/optimizely-sdk/lib/utils/enums/index.ts
  packages/optimizely-sdk/lib/utils/execution_context/index.ts
  packages/optimizely-sdk/lib/utils/http_request_handler/request_handler_factory.ts
Labels: bug

#786 feat: ODP REST API for Sending ODP Events
  packages/optimizely-sdk/lib/plugins/odp/graphql_manager.ts
  packages/optimizely-sdk/lib/plugins/odp/odp_client.ts
  packages/optimizely-sdk/lib/plugins/odp/odp_event.ts
  packages/optimizely-sdk/lib/plugins/odp/odp_response_schema.ts
  packages/optimizely-sdk/lib/plugins/odp/query_segments_parameters.ts
  packages/optimizely-sdk/lib/plugins/odp/rest_api_manager.ts
  packages/optimizely-sdk/lib/utils/enums/index.ts
  packages/optimizely-sdk/lib/utils/http_request_handler/browser_request_handler.ts
  packages/optimizely-sdk/lib/utils/http_request_handler/config.ts
  packages/optimizely-sdk/lib/utils/http_request_handler/http.ts
  packages/optimizely-sdk/lib/utils/http_request_handler/node_request_handler.ts
  packages/optimizely-sdk/lib/utils/http_request_handler/request_handler_factory.ts
  packages/optimizely-sdk/tests/graphQLManager.spec.ts
  packages/optimizely-sdk/tests/graphQlManager.spec.ts
  packages/optimizely-sdk/tests/odpClient.spec.ts
  packages/optimizely-sdk/tests/restApiManager.spec.ts
Labels: feature

#788 chore : updated prefix of ticket-check action
  .github/workflows/ticket_reference_check.yml
Labels: chore
