Repository optimizely/javascript-sdk, pull requests merged in 2023-05, with the labels that each got.

#820 [FSSDK-9152] Fix "client_initialized" event not firing
  packages/optimizely-sdk/lib/core/odp/odp_event_manager.ts
  packages/optimizely-sdk/lib/index.browser.tests.js
  packages/optimizely-sdk/tests/odpEventManager.spec.ts
Labels: bug

#823 [FSSDK-8950] change identifiers to be required for sendOdpEvent
  packages/optimizely-sdk/lib/core/odp/odp_event_manager.ts
  packages/optimizely-sdk/lib/plugins/odp/event_manager/index.browser.ts
  packages/optimizely-sdk/lib/plugins/odp/event_manager/index.node.ts
  packages/optimizely-sdk/tests/odpEventManager.spec.ts
Labels: feature

#825 [FSSDK-9032] enhancement: Add VUID instantiation to browser client promise dependencies
  packages/optimizely-sdk/lib/optimizely/index.ts
  packages/optimizely-sdk/lib/plugins/odp/event_api_manager/index.browser.ts
  packages/optimizely-sdk/lib/plugins/odp/event_api_manager/index.node.ts
  packages/optimizely-sdk/lib/utils/fns/index.ts
Labels: enhancement
