Repository optimizely/javascript-sdk, pull requests merged in 2024-03, with the labels that each got.

#914 [FSSDK-9621] add persistentCacheProvider option for instantiation
  lib/index.react_native.ts
  lib/modules/event_processor/reactNativeEventsStore.ts
  lib/modules/event_processor/v1/v1EventProcessor.react_native.ts
  lib/plugins/datafile_manager/react_native_http_polling_datafile_manager.ts
  lib/shared_types.ts
  package-lock.json
  package.json
  tests/reactNativeDatafileManger.spec.ts
  tests/reactNativeEventsStore.spec.ts
  tests/reactNativeHttpPollingDatafileManager.spec.ts
  tests/reactNativeV1EventProcessor.spec.ts
  tests/testUtils.ts
Labels: :robot: 4 hrs

#916 [FSSDK-9984] fix: Empty fetched qualified segments validity
  lib/optimizely_user_context/index.tests.js
  lib/optimizely_user_context/index.ts
Labels: bug

#918 [FSSDK-9965] chore: npm audit fix for follow-redirects & get-func-name
  package-lock.json
Labels: chore

#919 [FSSDK-9984] chore: Prep release
  CHANGELOG.md
  lib/index.browser.tests.js
  lib/index.lite.tests.js
  lib/index.node.tests.js
  lib/utils/enums/index.ts
  package-lock.json
  package.json
  tests/index.react_native.spec.ts
Labels: chore
